# docker-compose.yml
version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      DB_HOST: postgress
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - my-network

  postgres:
    image: postgres:16
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - my-network

networks:
  my-network:
